using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using Mutiny.Levels;
using Mutiny.Presentation;
using Mutiny.Simulation;
using UnityEngine;
using Object = UnityEngine.Object;

namespace Mutiny.Verification
{
    public static class MutinyAiStrategyVerificationTest
    {
        internal static readonly string[] Weapons = { "cherryBomb", "boulder", "dynamite", "piecesOfEight",
            "rumBottle", "banana", "parachuteBomb", "woodenCrate", "gunpowderBarrel", "seagull", "mine",
            "cannon", "anchor", "voodooDoll", "tidalWave" };
        internal static readonly int[] Lucks = { 0, 1, 7, 33 };
        internal static string BaselineDirectory => Path.Combine(Application.persistentDataPath, "ai-strategy-baseline-10c99ea");
        [Serializable] public sealed class BaselineEntry { public int Luck; public string Weapon, Sha256; }
        [Serializable] public sealed class BaselineManifest { public string Commit; public int Seed; public BaselineEntry[] Entries; }

        // Run this on the unmodified 10c99ea decision implementation before the
        // strategy refactor. The files are evidence, never generated by the test
        // that later compares the refactored production entry point.
        public static MutinyLevel1VerificationResult CaptureBaseline()
        {
            if (typeof(MutinyAIController).GetProperty("EnhancementEnabled") != null)
                throw new InvalidOperationException("Capture baseline on unmodified 10c99ea, not the strategy implementation.");
            var result = new MutinyLevel1VerificationResult();
            int forced = MutinyAIController.ForcedWeaponId;
            var random = UnityEngine.Random.state;
            try
            {
                MutinyAIController.TrySetForcedWeaponId(0);
                Directory.CreateDirectory(BaselineDirectory);
                foreach (int luck in Lucks)
                    using (var fixture = new MutinyAiResponsiveSearchVerificationTest.Fixture(luck))
                        foreach (string weapon in Weapons)
                        {
                            fixture.Actor.WeaponInventory.Clear();
                            fixture.Actor.AddWeapon(weapon, 5);
                            fixture.Ai.EvaluateBestMove();
                            string path = Path.Combine(BaselineDirectory, luck + "-" + weapon + ".json");
                            File.WriteAllText(path, JsonUtility.ToJson(fixture.Ai.LastDecisionTrace));
                            result.Assert(File.Exists(path), "AI-STRATEGY-BASELINE " + luck + "/" + weapon);
                        }
            }
            finally
            {
                MutinyAIController.TrySetForcedWeaponId(forced);
                UnityEngine.Random.state = random;
            }
            return result;
        }

        public static IEnumerator Run(MutinyLevel1VerificationResult result)
        {
            bool enhancement = MutinyAIController.EnhancementEnabled;
            int forced = MutinyAIController.ForcedWeaponId;
            bool logging = MutinyAIController.ActionLogEnabled;
            var random = UnityEngine.Random.state;
            try
            {
                result.Assert(!enhancement, "EXT-AI-STRAT-01 new Play Mode defaults to legacy");
                var gm = MutinyGMManager.Instance;
                result.Assert(gm != null, "GM-14 production GM singleton is available");
                if (gm == null) yield break;
                MutinyAIController.TrySetForcedWeaponId(0);
                MutinyAIController.SetActionLogEnabled(false);
                RunCommands(result, gm);
                RunBaselineComparisons(result, gm);
                foreach (object step in RunSearchSwitch(result, gm, false)) yield return step;
                foreach (object step in RunSearchSwitch(result, gm, true)) yield return step;
                foreach (object step in RunAbaSwitch(result, gm)) yield return step;
                foreach (object step in RunCameraSwitch(result, gm)) yield return step;
                foreach (object step in RunJumpSwitch(result, gm)) yield return step;
                foreach (object step in RunCoinSequence(result, gm)) yield return step;
                foreach (object step in RunNativeAndRestart(result, gm)) yield return step;
            }
            finally
            {
                MutinyAIController.SetEnhancementEnabled(enhancement);
                MutinyAIController.TrySetForcedWeaponId(forced);
                MutinyAIController.SetActionLogEnabled(logging);
                UnityEngine.Random.state = random;
            }
        }

        private static void RunCommands(MutinyLevel1VerificationResult result, MutinyGMManager gm)
        {
            gm.ExecuteCommand("aienhance 0");
            int version = MutinyAIController.StrategyConfigurationVersion;
            result.Assert(gm.ExecuteCommand("  AIEnhance   1  ") && MutinyAIController.EnhancementEnabled &&
                MutinyAIController.StrategyConfigurationVersion == version + 1 &&
                MutinyAIController.EnhancedPlannerImplemented && Status(gm).Contains("effects-v1"),
                "GM-14 enable routes full effects-v1 and explicitly discloses model limits");
            version = MutinyAIController.StrategyConfigurationVersion;
            result.Assert(gm.ExecuteCommand("aienhance 1") && MutinyAIController.StrategyConfigurationVersion == version,
                "EXT-AI-STRAT-03 repeated same setting does not invalidate decisions");
            foreach (string command in new[] { "aienhance", "aienhance 2", "aienhance -1", "aienhance true", "aienhance 0 extra", "aienhancex 0" })
                result.Assert(!gm.ExecuteCommand(command) && MutinyAIController.EnhancementEnabled &&
                    MutinyAIController.StrategyConfigurationVersion == version,
                    "GM-14 invalid input preserves strategy state: " + command);
            result.Assert(gm.ExecuteCommand("aienhance 0") && !MutinyAIController.EnhancementEnabled,
                "GM-14 disable selects legacy");
            result.Assert(gm.ExecuteCommand("aienhance 1") && MutinyAIController.EnhancementEnabled,
                "GM-14 production command can re-enable enhanced strategy");
            result.Assert(gm.ExecuteCommand("help") && Status(gm).Contains("aienhance"), "GM-14 Help documents strategy command");
            using (var fixture = new MutinyAiResponsiveSearchVerificationTest.Fixture(7))
            {
                float luck = fixture.Actor.Luck;
                int ammunition = fixture.Actor.WeaponInventory["cherryBomb"];
                gm.ExecuteCommand("aienhance 0");
                gm.ExecuteCommand("aienhance 1");
                result.Assert(!fixture.Team.IsAiControlled && fixture.Actor.Luck == luck &&
                    fixture.Actor.WeaponInventory["cherryBomb"] == ammunition,
                    "EXT-AI-STRAT-01 switching does not take over humans or mutate Luck/inventory");
                result.Assert(gm.ExecuteCommand("aiforceusewaepon 1") && gm.ExecuteCommand("ailog 1") &&
                    MutinyAIController.EnhancementEnabled && MutinyAIController.ForcedWeaponId == 1 && MutinyAIController.ActionLogEnabled,
                    "GM-14 forced weapon/logging remain independent settings");
                gm.ExecuteCommand("aiforceusewaepon 0");
                gm.ExecuteCommand("ailog 0");
            }
        }

        private static void RunBaselineComparisons(MutinyLevel1VerificationResult result, MutinyGMManager gm)
        {
            TextAsset asset = Resources.Load<TextAsset>("Verification/ai-strategy-baseline-10c99ea");
            BaselineManifest baseline = asset != null ? JsonUtility.FromJson<BaselineManifest>(asset.text) : null;
            result.Assert(baseline != null && baseline.Commit == "10c99ea461ba1bd528c5739119521cdcd2888c56" &&
                baseline.Seed == 13731 && baseline.Entries.Length == 60,
                "EXT-AI-STRAT-02 committed pre-refactor baseline evidence is available");
            if (baseline == null) return;
            // Effects-v1 intentionally differs. Preserve the independent Legacy
            // evidence and check it on both sides of a real GM mode switch.
            foreach (bool switched in new[] { false, true })
            {
                if (switched) gm.ExecuteCommand("aienhance 1");
                gm.ExecuteCommand("aienhance 0");
                foreach (int luck in Lucks)
                    using (var fixture = new MutinyAiResponsiveSearchVerificationTest.Fixture(luck))
                        foreach (string weapon in Weapons)
                        {
                            fixture.Actor.WeaponInventory.Clear(); fixture.Actor.AddWeapon(weapon, 5);
                            AIMove move = fixture.Ai.EvaluateBestMove();
                            BaselineEntry expected = Array.Find(baseline.Entries, entry => entry.Luck == luck && entry.Weapon == weapon);
                            result.Assert(expected != null && expected.Sha256 == Checksum(JsonUtility.ToJson(fixture.Ai.LastDecisionTrace)),
                                "EXT-AI-STRAT-02 complete 10c99ea legacy trace unchanged after switch " + luck + "/" + weapon);
                            result.Assert(move.StrategyContext.IsBound && move.StrategyContext.Mode ==
                                MutinyAIStrategyMode.Legacy && !move.StrategyContext.UsesFallback &&
                                move.StrategyContext.AlgorithmId == "legacy" && fixture.Ai.LastDecisionStrategy.StrategyId == "legacy",
                                "EXT-AI-STRAT-02 result carries selected immutable strategy " + luck + "/" + weapon);
                        }
            }
        }

        private static IEnumerable<object> RunSearchSwitch(MutinyLevel1VerificationResult result, MutinyGMManager gm, bool startEnhanced)
        {
            gm.ExecuteCommand(startEnhanced ? "aienhance 1" : "aienhance 0");
            using (var fixture = new MutinyAiResponsiveSearchVerificationTest.Fixture(99999, runtime: true))
            {
                fixture.Ai.SaveDecisionTrace = true;
                // Effects-v1 intentionally bounds high luck. A small real pump
                // budget makes cancellation observable even on a fast machine.
                fixture.Ai.DecisionBudgetMilliseconds = 0.1f;
                var manager = fixture.Host.AddComponent<MutinyTurnManager>(); manager.Initialize(fixture.Team, fixture.EnemyTeam);
                result.Assert(gm.ExecuteCommand("aitakeover 99999"), "EXT-AI-STRAT-03 start real GM takeover search");
                double deadline = Time.realtimeSinceStartupAsDouble + 15;
                while (fixture.Ai.EvaluatedCandidateCount < 100 && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                var before = fixture.Ai.CurrentDecisionStrategy;
                string canceledPath = fixture.Ai.CurrentDecisionTracePath;
                int invalidations = fixture.Ai.InvalidatedDecisionCount;
                int ammunition = fixture.Actor.WeaponInventory["cherryBomb"];
                result.Assert(before.IsBound && before.Mode == (startEnhanced ? MutinyAIStrategyMode.Enhanced : MutinyAIStrategyMode.Legacy),
                    "EXT-AI-STRAT-03 live search uses requested initial route");
                gm.ExecuteCommand(startEnhanced ? "aienhance 1" : "aienhance 0");
                yield return null;
                result.Assert(fixture.Ai.InvalidatedDecisionCount == invalidations &&
                    fixture.Ai.CurrentDecisionStrategy.ConfigurationVersion == before.ConfigurationVersion,
                    "EXT-AI-STRAT-03 identical setting keeps live work");
                gm.ExecuteCommand(startEnhanced ? "aienhance 0" : "aienhance 1");
                deadline = Time.realtimeSinceStartupAsDouble + 10;
                while (fixture.Ai.InvalidatedDecisionCount == invalidations && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                result.Assert(fixture.Ai.InvalidatedDecisionCount > invalidations && fixture.Ai.LastDecisionInvalidationReason == "ai-strategy" &&
                    fixture.Actor.WeaponInventory["cherryBomb"] == ammunition && !fixture.Ai.LastCommittedStrategy.IsBound,
                    "EXT-AI-STRAT-03 GM switch cancels old live work without submitting/deducting");
                result.Assert(canceledPath != null && !File.Exists(canceledPath),
                    "EXT-AI-STRAT-05 canceled strategy search does not publish a complete trace");
                deadline = Time.realtimeSinceStartupAsDouble + 30;
                while (!fixture.Ai.LastCommittedStrategy.IsBound && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                result.Assert(fixture.Ai.LastCommittedStrategy.IsBound && fixture.Ai.LastCommittedStrategy.Mode ==
                    (startEnhanced ? MutinyAIStrategyMode.Legacy : MutinyAIStrategyMode.Enhanced),
                    "EXT-AI-STRAT-03 restarted production search commits only new strategy");
            }
            yield return null;
        }

        private static IEnumerable<object> RunAbaSwitch(MutinyLevel1VerificationResult result, MutinyGMManager gm)
        {
            gm.ExecuteCommand("aienhance 0");
            using (var fixture = new MutinyAiResponsiveSearchVerificationTest.Fixture(99999, runtime: true))
            {
                var manager = fixture.Host.AddComponent<MutinyTurnManager>(); manager.Initialize(fixture.Team, fixture.EnemyTeam);
                gm.ExecuteCommand("aitakeover 99999");
                double deadline = Time.realtimeSinceStartupAsDouble + 10;
                while (fixture.Ai.EvaluatedCandidateCount < 100 && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                int version = fixture.Ai.CurrentDecisionStrategy.ConfigurationVersion;
                gm.ExecuteCommand("aienhance 1"); gm.ExecuteCommand("aienhance 0");
                deadline = Time.realtimeSinceStartupAsDouble + 10;
                while (fixture.Ai.InvalidatedDecisionCount == 0 && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                result.Assert(!MutinyAIController.EnhancementEnabled && MutinyAIController.StrategyConfigurationVersion == version + 2 &&
                    fixture.Ai.InvalidatedDecisionCount > 0 && fixture.Ai.LastDecisionInvalidationReason == "ai-strategy" &&
                    !fixture.Ai.LastCommittedStrategy.IsBound,
                    "EXT-AI-STRAT-03 off/on/off between frames cannot revive an old decision");
                fixture.Ai.enabled = false;
            }
            yield return null;
        }

        private static IEnumerable<object> RunCameraSwitch(MutinyLevel1VerificationResult result, MutinyGMManager gm)
        {
            gm.ExecuteCommand("aienhance 0");
            using (var fixture = new MutinyAiResponsiveSearchVerificationTest.Fixture(7, runtime: true))
            {
                var manager = fixture.Host.AddComponent<MutinyTurnManager>(); manager.Initialize(fixture.Team, fixture.EnemyTeam);
                var cameraObject = new GameObject("StrategyCamera"); cameraObject.transform.SetParent(fixture.Host.transform);
                cameraObject.AddComponent<Camera>().orthographic = true;
                var camera = cameraObject.AddComponent<MutinyCameraController>(); camera.enabled = false;
                gm.ExecuteCommand("aitakeover 7");
                double deadline = Time.realtimeSinceStartupAsDouble + 10;
                while (!camera.IsPanningToTurnTarget && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                int ammunition = fixture.Actor.WeaponInventory["cherryBomb"];
                result.Assert(camera.IsPanningToTurnTarget && fixture.Ai.LastDecisionStrategy.IsBound &&
                    !fixture.Ai.LastCommittedStrategy.IsBound, "EXT-AI-STRAT-03 winner is waiting at real camera gate");
                gm.ExecuteCommand("aienhance 1");
                deadline = Time.realtimeSinceStartupAsDouble + 10;
                while (fixture.Ai.InvalidatedDecisionCount == 0 && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                result.Assert(fixture.Ai.InvalidatedDecisionCount > 0 && fixture.Ai.LastDecisionInvalidationReason == "ai-strategy" &&
                    !fixture.Ai.LastCommittedStrategy.IsBound && fixture.Actor.WeaponInventory["cherryBomb"] == ammunition,
                    "EXT-AI-STRAT-03 switch during camera wait cannot commit the old winner");
                Object.DestroyImmediate(cameraObject);
                deadline = Time.realtimeSinceStartupAsDouble + 10;
                while (!fixture.Ai.LastCommittedStrategy.IsBound && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                result.Assert(fixture.Ai.LastCommittedStrategy.Mode == MutinyAIStrategyMode.Enhanced && fixture.Ai.LastCommittedStrategy.IsBound,
                    "EXT-AI-STRAT-03 new route submits after the camera gate is released");
            }
            yield return null;
        }

        private static IEnumerable<object> RunJumpSwitch(MutinyLevel1VerificationResult result, MutinyGMManager gm)
        {
            gm.ExecuteCommand("aienhance 0");
            using (var fixture = new MutinyAiResponsiveSearchVerificationTest.Fixture(7, runtime: true))
            {
                var manager = fixture.Host.AddComponent<MutinyTurnManager>(); manager.Initialize(fixture.Team, fixture.EnemyTeam);
                fixture.Team.SelectCharacter(fixture.Actor);
                fixture.Ai.ExecuteMoveForVerification(new AIMove { Character = fixture.Actor,
                    MoveType = AIMoveType.SelfThrow, LaunchVelocity = new Vector2(0, -7) }, manager);
                gm.ExecuteCommand("aienhance 1");
                result.Assert(!fixture.Team.IsAiControlled && !fixture.Actor.CanThrow && fixture.Actor.CanShoot,
                    "EXT-AI-STRAT-04 switch leaves a committed human jump and shooting eligibility intact");
                result.Assert(gm.ExecuteCommand("aitakeover 7"), "EXT-AI-STRAT-04 takeover remains legal during real jump");
                gm.ExecuteCommand("aienhance 0");
                double deadline = Time.realtimeSinceStartupAsDouble + 15;
                while (fixture.Ai.LastDecisionTrace == null && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                while (fixture.Actor.CanShoot && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                result.Assert(fixture.Ai.LastDecisionTrace != null && fixture.Ai.LastDecisionTrace.Phase == "continuation" &&
                    fixture.Team.SelectedCharacter == fixture.Actor && !fixture.Actor.CanThrow && !fixture.Actor.CanShoot &&
                    fixture.Ai.LastCommittedStrategy.IsBound && fixture.Ai.LastCommittedStrategy.Mode == MutinyAIStrategyMode.Legacy,
                    "EXT-AI-STRAT-04 after jump settlement only same actor's remaining shot uses the latest route");
            }
            yield return null;
        }

        private static IEnumerable<object> RunCoinSequence(MutinyLevel1VerificationResult result, MutinyGMManager gm)
        {
            gm.ExecuteCommand("aienhance 1"); gm.ExecuteCommand("ailog 1");
            using (var fixture = new MutinyAiResponsiveSearchVerificationTest.Fixture(100, runtime: true))
            {
                fixture.Actor.WeaponInventory.Clear(); fixture.Actor.AddWeapon("piecesOfEight", 5);
                // High initial health avoids turning a sequence identity test into
                // a self-kill/early victory case; all hits still use real damage.
                fixture.Actor.Health = fixture.Actor.MaxHealth = fixture.Actor.ShownHealth = 1000;
                fixture.Enemy.Health = fixture.Enemy.MaxHealth = fixture.Enemy.ShownHealth = 1000;
                var manager = fixture.Host.AddComponent<MutinyTurnManager>(); manager.Initialize(fixture.Team, fixture.EnemyTeam);
                var logs = new List<string>();
                Application.LogCallback capture = (message, stack, type) => { if (message.StartsWith("[Mutiny:AI-Action]")) logs.Add(message); };
                Application.logMessageReceived += capture;
                try
                {
                    gm.ExecuteCommand("aitakeover 100");
                    MutinyPiecesOfEight coins = null;
                    double deadline = Time.realtimeSinceStartupAsDouble + 15;
                    while (coins == null && Time.realtimeSinceStartupAsDouble < deadline)
                    {
                        foreach (var candidate in Object.FindObjectsByType<MutinyPiecesOfEight>())
                            if (candidate.Owner == fixture.Actor && candidate.IsFired) { coins = candidate; break; }
                        if (coins == null) yield return null;
                    }
                    result.Assert(coins != null, "EXT-AI-STRAT-04 real planner commits the coin weapon");
                    if (coins == null) yield break;
                    var identity = coins.AiStrategyContext;
                    bool finished = false; int total = 0;
                    MutinyAIStrategyContext finishedIdentity = default;
                    coins.OnFinished += () => { finished = true; total = coins.TimesFired; finishedIdentity = coins.AiStrategyContext; };
                    gm.ExecuteCommand("aienhance 0");
                    result.Assert(identity.IsBound && identity.Mode == MutinyAIStrategyMode.Enhanced && !identity.UsesFallback &&
                        coins.AiStrategyContext.ConfigurationVersion == identity.ConfigurationVersion &&
                        fixture.Actor.WeaponInventory["piecesOfEight"] == 4,
                        "EXT-AI-STRAT-04 submitted coin sequence retains enhanced identity and one inventory debit");
                    deadline = Time.realtimeSinceStartupAsDouble + 60;
                    while (!finished && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                    result.Assert(finished && total == 8 && finishedIdentity.ConfigurationVersion == identity.ConfigurationVersion &&
                        finishedIdentity.Mode == MutinyAIStrategyMode.Enhanced && fixture.Actor.WeaponInventory["piecesOfEight"] == 4,
                        "EXT-AI-STRAT-04 all eight coins finish under latched identity after GM disable");
                    int continuations = 0; bool identityLogged = logs.Count > 0;
                    foreach (string log in logs)
                    {
                        if (log.Contains("action=CoinContinuation")) continuations++;
                        identityLogged &= log.Contains("mode=enhanced") && log.Contains("strategy=enhanced-effects-v1") &&
                            log.Contains("algorithm=effects-v1") && log.Contains("fallback=False");
                    }
                    result.Assert(continuations == 7 && identityLogged,
                        "EXT-AI-STRAT-05 committed action log distinguishes effects-v1 from legacy algorithm");
                }
                finally { Application.logMessageReceived -= capture; }
            }
            gm.ExecuteCommand("ailog 0");
            yield return null;
        }

        private static IEnumerable<object> RunNativeAndRestart(MutinyLevel1VerificationResult result, MutinyGMManager gm)
        {
            gm.ExecuteCommand("aienhance 1"); gm.ExecuteCommand("aiforceusewaepon 15");
            using (var fixture = new MutinyAiResponsiveSearchVerificationTest.Fixture(7, runtime: true))
            {
                var native = fixture.EnemyTeam.gameObject.AddComponent<MutinyAIController>(); native.enabled = false;
                native.SaveDecisionTrace = false;
                var manager = fixture.Host.AddComponent<MutinyTurnManager>(); manager.Initialize(fixture.Team, fixture.EnemyTeam);
                manager.PassTurn();
                double deadline = Time.realtimeSinceStartupAsDouble + 10;
                while (manager.CurrentTeam != fixture.EnemyTeam && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                native.enabled = true;
                deadline = Time.realtimeSinceStartupAsDouble + 10;
                while (!native.LastCommittedStrategy.IsBound && Time.realtimeSinceStartupAsDouble < deadline) yield return null;
                result.Assert(native.LastCommittedStrategy.IsBound && native.LastCommittedStrategy.Mode == MutinyAIStrategyMode.Enhanced &&
                    !native.LastCommittedStrategy.UsesFallback && !fixture.Team.IsAiControlled,
                    "EXT-AI-STRAT-02 native enemy AI uses selected route without human takeover");
                native.enabled = false;
            }
            gm.ExecuteCommand("aiforceusewaepon 0");
            yield return null;
            var host = new GameObject("StrategyRestartFixture");
            var controller = host.AddComponent<MutinyLevelController>(); controller.enabled = false;
            try
            {
                bool loaded = controller.TryLoadLevel(7);
                result.Assert(loaded, "EXT-AI-STRAT-01 load actual single-player level for settings lifecycle");
                if (loaded)
                {
                    result.Assert(gm.ExecuteCommand("aisetluck 7") && MutinyAIController.EnhancementEnabled,
                        "EXT-AI-STRAT-01 level Luck setting does not change strategy mode");
                    controller.RestartCurrentLevel();
                    result.Assert(MutinyAIController.EnhancementEnabled,
                        "EXT-AI-STRAT-01 actual level restart retains session strategy setting");
                }
            }
            finally { Object.DestroyImmediate(host); MutinyBoxRegistry.ResetForLevel(); }
            yield return null;
        }

        private static string Status(MutinyGMManager gm) =>
            (string)typeof(MutinyGMManager).GetField("m_StatusMessage", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(gm);
        private static string Checksum(string json)
        {
            using (SHA256 sha = SHA256.Create())
                return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(json))).Replace("-", "").ToLowerInvariant();
        }
    }
}
